# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vision/color.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class color(genpy.Message):
  _md5sum = "3ff80881ed080689369689eeb69893cd"
  _type = "vision/color"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int64 ColorMode
int64[] BallHSVBox
int64[] GreenHSVBox
int64[] BlueHSVBox
int64[] YellowHSVBox
int64[] WhiteHSVBox
"""
  __slots__ = ['ColorMode','BallHSVBox','GreenHSVBox','BlueHSVBox','YellowHSVBox','WhiteHSVBox']
  _slot_types = ['int64','int64[]','int64[]','int64[]','int64[]','int64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ColorMode,BallHSVBox,GreenHSVBox,BlueHSVBox,YellowHSVBox,WhiteHSVBox

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(color, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ColorMode is None:
        self.ColorMode = 0
      if self.BallHSVBox is None:
        self.BallHSVBox = []
      if self.GreenHSVBox is None:
        self.GreenHSVBox = []
      if self.BlueHSVBox is None:
        self.BlueHSVBox = []
      if self.YellowHSVBox is None:
        self.YellowHSVBox = []
      if self.WhiteHSVBox is None:
        self.WhiteHSVBox = []
    else:
      self.ColorMode = 0
      self.BallHSVBox = []
      self.GreenHSVBox = []
      self.BlueHSVBox = []
      self.YellowHSVBox = []
      self.WhiteHSVBox = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_q.pack(self.ColorMode))
      length = len(self.BallHSVBox)
      buff.write(_struct_I.pack(length))
      pattern = '<%sq'%length
      buff.write(struct.pack(pattern, *self.BallHSVBox))
      length = len(self.GreenHSVBox)
      buff.write(_struct_I.pack(length))
      pattern = '<%sq'%length
      buff.write(struct.pack(pattern, *self.GreenHSVBox))
      length = len(self.BlueHSVBox)
      buff.write(_struct_I.pack(length))
      pattern = '<%sq'%length
      buff.write(struct.pack(pattern, *self.BlueHSVBox))
      length = len(self.YellowHSVBox)
      buff.write(_struct_I.pack(length))
      pattern = '<%sq'%length
      buff.write(struct.pack(pattern, *self.YellowHSVBox))
      length = len(self.WhiteHSVBox)
      buff.write(_struct_I.pack(length))
      pattern = '<%sq'%length
      buff.write(struct.pack(pattern, *self.WhiteHSVBox))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 8
      (self.ColorMode,) = _struct_q.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sq'%length
      start = end
      end += struct.calcsize(pattern)
      self.BallHSVBox = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sq'%length
      start = end
      end += struct.calcsize(pattern)
      self.GreenHSVBox = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sq'%length
      start = end
      end += struct.calcsize(pattern)
      self.BlueHSVBox = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sq'%length
      start = end
      end += struct.calcsize(pattern)
      self.YellowHSVBox = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sq'%length
      start = end
      end += struct.calcsize(pattern)
      self.WhiteHSVBox = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_q.pack(self.ColorMode))
      length = len(self.BallHSVBox)
      buff.write(_struct_I.pack(length))
      pattern = '<%sq'%length
      buff.write(self.BallHSVBox.tostring())
      length = len(self.GreenHSVBox)
      buff.write(_struct_I.pack(length))
      pattern = '<%sq'%length
      buff.write(self.GreenHSVBox.tostring())
      length = len(self.BlueHSVBox)
      buff.write(_struct_I.pack(length))
      pattern = '<%sq'%length
      buff.write(self.BlueHSVBox.tostring())
      length = len(self.YellowHSVBox)
      buff.write(_struct_I.pack(length))
      pattern = '<%sq'%length
      buff.write(self.YellowHSVBox.tostring())
      length = len(self.WhiteHSVBox)
      buff.write(_struct_I.pack(length))
      pattern = '<%sq'%length
      buff.write(self.WhiteHSVBox.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 8
      (self.ColorMode,) = _struct_q.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sq'%length
      start = end
      end += struct.calcsize(pattern)
      self.BallHSVBox = numpy.frombuffer(str[start:end], dtype=numpy.int64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sq'%length
      start = end
      end += struct.calcsize(pattern)
      self.GreenHSVBox = numpy.frombuffer(str[start:end], dtype=numpy.int64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sq'%length
      start = end
      end += struct.calcsize(pattern)
      self.BlueHSVBox = numpy.frombuffer(str[start:end], dtype=numpy.int64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sq'%length
      start = end
      end += struct.calcsize(pattern)
      self.YellowHSVBox = numpy.frombuffer(str[start:end], dtype=numpy.int64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sq'%length
      start = end
      end += struct.calcsize(pattern)
      self.WhiteHSVBox = numpy.frombuffer(str[start:end], dtype=numpy.int64, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_q = struct.Struct("<q")
