#!/bin/bash

ifconfig > host

host0=eth4 #可能要修改
host1=eth5 #可能要修改

host=$(grep "wlan" host)
host2=${host:0:6} #For WIFI
#host2=wlan1

name=TKU_IARC #ip分享器名稱
passwd=1234567890 #ip分享器密碼

sudo /etc/init.d/network-manager stop

sudo ifconfig $host0 192.168.16.100 up #Ethernet
sudo route add -host 192.168.16.11 dev $host0 #Camera
sudo ifconfig $host1 192.168.2.100 up #Ethernet
sudo route add -host 192.168.2.34 dev $host1 #FPGA

sudo ifconfig $host2 up
sudo wpa_passphrase $name $passwd > wpa.conf
sudo wpa_supplicant -BDwext -i $host2 -c wpa.conf
sudo ifconfig $host2 192.168.0.100 #WIFI
sudo dhclient $host2
