// Generated by gencpp from file vision/black.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_BLACK_H
#define VISION_MESSAGE_BLACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct black_
{
  typedef black_<ContainerAllocator> Type;

  black_()
    : Gray(0)
    , Angle(0)  {
    }
  black_(const ContainerAllocator& _alloc)
    : Gray(0)
    , Angle(0)  {
  (void)_alloc;
    }



   typedef int64_t _Gray_type;
  _Gray_type Gray;

   typedef int64_t _Angle_type;
  _Angle_type Angle;




  typedef boost::shared_ptr< ::vision::black_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::black_<ContainerAllocator> const> ConstPtr;

}; // struct black_

typedef ::vision::black_<std::allocator<void> > black;

typedef boost::shared_ptr< ::vision::black > blackPtr;
typedef boost::shared_ptr< ::vision::black const> blackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::black_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::black_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'vision': ['/home/leokim/interface_ws/src/interface_ws/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::black_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::black_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::black_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::black_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::black_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::black_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::black_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5dea6a3e5a1346d96db1f873a7e99b4e";
  }

  static const char* value(const ::vision::black_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5dea6a3e5a1346d9ULL;
  static const uint64_t static_value2 = 0x6db1f873a7e99b4eULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::black_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/black";
  }

  static const char* value(const ::vision::black_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::black_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 Gray\n\
int64 Angle\n\
";
  }

  static const char* value(const ::vision::black_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::black_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Gray);
      stream.next(m.Angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct black_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::black_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::black_<ContainerAllocator>& v)
  {
    s << indent << "Gray: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Gray);
    s << indent << "Angle: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_BLACK_H
