// Generated by gencpp from file vision/camera.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_CAMERA_H
#define VISION_MESSAGE_CAMERA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct camera_
{
  typedef camera_<ContainerAllocator> Type;

  camera_()
    : fps(0)  {
    }
  camera_(const ContainerAllocator& _alloc)
    : fps(0)  {
  (void)_alloc;
    }



   typedef int64_t _fps_type;
  _fps_type fps;




  typedef boost::shared_ptr< ::vision::camera_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::camera_<ContainerAllocator> const> ConstPtr;

}; // struct camera_

typedef ::vision::camera_<std::allocator<void> > camera;

typedef boost::shared_ptr< ::vision::camera > cameraPtr;
typedef boost::shared_ptr< ::vision::camera const> cameraConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::camera_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::camera_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'vision': ['/home/leokim/interface_ws/src/interface_ws/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::camera_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::camera_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::camera_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::camera_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::camera_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::camera_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0744f9079f53d1596660372505b379c3";
  }

  static const char* value(const ::vision::camera_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0744f9079f53d159ULL;
  static const uint64_t static_value2 = 0x6660372505b379c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/camera";
  }

  static const char* value(const ::vision::camera_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 fps\n\
";
  }

  static const char* value(const ::vision::camera_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::camera_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct camera_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::camera_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::camera_<ContainerAllocator>& v)
  {
    s << indent << "fps: ";
    Printer<int64_t>::stream(s, indent + "  ", v.fps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_CAMERA_H
