// Generated by gencpp from file vision/colorbutton.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_COLORBUTTON_H
#define VISION_MESSAGE_COLORBUTTON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct colorbutton_
{
  typedef colorbutton_<ContainerAllocator> Type;

  colorbutton_()
    : button(0)  {
    }
  colorbutton_(const ContainerAllocator& _alloc)
    : button(0)  {
  (void)_alloc;
    }



   typedef int64_t _button_type;
  _button_type button;




  typedef boost::shared_ptr< ::vision::colorbutton_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::colorbutton_<ContainerAllocator> const> ConstPtr;

}; // struct colorbutton_

typedef ::vision::colorbutton_<std::allocator<void> > colorbutton;

typedef boost::shared_ptr< ::vision::colorbutton > colorbuttonPtr;
typedef boost::shared_ptr< ::vision::colorbutton const> colorbuttonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::colorbutton_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::colorbutton_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'vision': ['/home/leokim/interface_ws/src/interface_ws/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::colorbutton_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::colorbutton_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::colorbutton_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::colorbutton_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::colorbutton_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::colorbutton_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::colorbutton_<ContainerAllocator> >
{
  static const char* value()
  {
    return "636f342c16f994332c9e43675fa80a7c";
  }

  static const char* value(const ::vision::colorbutton_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x636f342c16f99433ULL;
  static const uint64_t static_value2 = 0x2c9e43675fa80a7cULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::colorbutton_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/colorbutton";
  }

  static const char* value(const ::vision::colorbutton_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::colorbutton_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 button\n\
";
  }

  static const char* value(const ::vision::colorbutton_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::colorbutton_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.button);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct colorbutton_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::colorbutton_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::colorbutton_<ContainerAllocator>& v)
  {
    s << indent << "button: ";
    Printer<int64_t>::stream(s, indent + "  ", v.button);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_COLORBUTTON_H
