// Generated by gencpp from file vision/parametercheck.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_PARAMETERCHECK_H
#define VISION_MESSAGE_PARAMETERCHECK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct parametercheck_
{
  typedef parametercheck_<ContainerAllocator> Type;

  parametercheck_()
    : checkpoint(0)  {
    }
  parametercheck_(const ContainerAllocator& _alloc)
    : checkpoint(0)  {
  (void)_alloc;
    }



   typedef int64_t _checkpoint_type;
  _checkpoint_type checkpoint;




  typedef boost::shared_ptr< ::vision::parametercheck_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::parametercheck_<ContainerAllocator> const> ConstPtr;

}; // struct parametercheck_

typedef ::vision::parametercheck_<std::allocator<void> > parametercheck;

typedef boost::shared_ptr< ::vision::parametercheck > parametercheckPtr;
typedef boost::shared_ptr< ::vision::parametercheck const> parametercheckConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::parametercheck_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::parametercheck_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'vision': ['/home/leokim/interface_ws/src/interface_ws/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::parametercheck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::parametercheck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::parametercheck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::parametercheck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::parametercheck_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::parametercheck_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::parametercheck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d5b7d9ec5b2f1f18019dbf18a79d4c9";
  }

  static const char* value(const ::vision::parametercheck_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d5b7d9ec5b2f1f1ULL;
  static const uint64_t static_value2 = 0x8019dbf18a79d4c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::parametercheck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/parametercheck";
  }

  static const char* value(const ::vision::parametercheck_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::parametercheck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 checkpoint\n\
";
  }

  static const char* value(const ::vision::parametercheck_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::parametercheck_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.checkpoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct parametercheck_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::parametercheck_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::parametercheck_<ContainerAllocator>& v)
  {
    s << indent << "checkpoint: ";
    Printer<int64_t>::stream(s, indent + "  ", v.checkpoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_PARAMETERCHECK_H
